dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn lint
  - yarn test:ci
  - yarn build