notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: NnuinN7bqGpjYZTBGbOwu/3DgZKFU5BipLftMbSwX1UsBRz+YM6zwRBBwuCSil4WBBk7tPDubVV0KHr4Mlti6OYaeCjRlJ5IKLJI8M1z64W5guVnMzeIfPjor+kElURVlMqyTGm2GQZaIQbvoj7AMRddbHQ2MH7F3jbxJRMGtW5p1cMoBUWtOrYkDKlSclJ5cVlMuZJIOfF+owOyQYXCnKX3Fg3yTRzAn7IczvVxVx2tXudUgFd3ZkuOiv3UhaIaJn/DPvZ7Daj+MQegIUbH+Rj+HKFRwUNr8l/YKBra7q/HInxr1cxgYG3Aiwwy412LPv0XscePYj4FYPB6m2X/Q/UBR+rHWVMjRApzdZND5xjZsVvWvdysB8xtUXzz2M2mIFjcV53CNgtMOHjzBFXbB6YOcr2kdWaqXuVWyGXL6iV40jgHJcCJ7S5DmpVzjw/eBsq4Lj6+lYeFyI8srMOywrXhwAbLLfZVtcUH2fas2YRrG1Svy4vEzUwaQeuBh+8V/bMM24qBWG0a4n2OAw47DXi2VpzroFkiOVxUSSvgo+XxH8dEhGfss3zdsEegWUIt/uKJSRHlCBFlJhKun/1VoT1kKab0ln1mz97yAp7ZmilEs23ev4qjXF173puVY+/j/slUHviUARCGAWRpHXGjsKsZZK9Bqb8vjGrAOHq81T0=
env:
  global:
  - secure: lhMsUtTmKwpvAIKtDTnSZiD4LOw2dD/hb7ZmNZIVutTMxU4yXE2T+6qJHNJWsNttHmUVrq6aDqxapWkZ54E70btiRI+ihMvOuPVMKMhZ0Jg0JKZfJDai5V4d/23FgmXuvNydpIZcEiY7UpGsWd7nOGGXasBBCNjU8twcQVk+YE+vHB1PxzO2iIEBCz/mcEFRDh5+tmtj9YlGR85Dz5NBdzOXSYkguW/cwMkrScBLsI4ELGgTzmuaXvXJVoUtd29LICf54r4xjeRyXCUCA8+ncqDFIWLLDoJoCXJnDbSdxAt4TjpwnRYkIKLSnc7jtQH+4riOox7SsIeB5DWqpwfg9SbAfGvoF/VDIjqcT1JYcXQ96111Ok0tAjH9MLf0Fjh2LhslfZQtsy55EIrF/KSyvB+ERJ3bAd7PASg+wYaoYvjBdYbTd/XPKZqB0xUw1pTCYe6ysvKPijQu3Qp4eXbRaOo9g2fGsLwsXp5owh8an9U+C3Jj22CGdicUzjQJN+fRvue0vhVQsv9YriQe084u+KMQRWrigc7l3Yuw8myh4zqYqThEsV4n3/o50piAeaXXWTlJiZ2tTetwH/+m2389bDnM+dMpYz2y7nbBsQ5ZNU4cmc/WJWT/ujq7+z9VOC9X71iuz7+7DL/As6T3upnwKV99un5htOyE3V48BxC51Q0=
  
branches:
  only:
  - master
  - develop
  - alpha-rti

language: node_js
node_js:
  - '12'

cache:
  directories:
  - "./node_modules"

# before_install:
#   - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
#   - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - if: branch=master
      env:
        ENV=staging
    - if: branch=develop
      env:
        ENV=dev
    - if: branch=alpha-rti
      env:
        ENV=staging

install:
  - yarn

script:
  - sh scripts/set-build-num.sh $TRAVIS_BUILD_NUMBER
  - yarn lint
  - yarn test:ci
  - yarn build

before_deploy:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

deploy:
  - provider: script
    script: sh scripts/publish.sh $ENV
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(develop|master)$
  - provider: script
    script: sh scripts/publish-prod.sh
    skip_cleanup: true
    on:
      branch: alpha-rti

after_deploy:
  - bash scripts/test_runner.sh widget $ENV
